### ISSUE TITLE
Nothing shows up in the stripclub

### ISSUE THREAD

**Issue by WoozyFace** [YeahItsHayden/qb-vanillaunicorn#1]
Like the title says...

**Comment by TheCorruptCode** [comment]
Be descriptive with your issue and any errors, multiple people have been able to use this without issues.

**Comment by The-Omen56** [comment]
Good day.

i am having the same problem. followed the install and setup but stash, duty and etc are showing. The bartender is there but cannot do anything with him.

is there any extra steps to follow?

**Comment by The-Omen56** [comment]
client_scripts {
    'config/cl_config.lua',

this file is in the fxmanifest.lua but not in the folder. is this just wrong or is it missing?
